package fnlock

// 密钥生命周期相关能力入口。
var whitelistBusinessKey = []LockedFunction{
	{
		ID:               "bitfs.managed.key.create_random",
		Module:           ModuleBitFS,
		Package:          "./pkg/managedclient",
		Symbol:           "managedDaemon.createRandomKeyMaterial",
		Signature:        "func (d *managedDaemon) createRandomKeyMaterial(password string) (keyMaterialTicket, error)",
		ObsControlAction: "key.create_random",
		Note:             "只负责创建随机密钥；已存在时直接报错，避免测试语义混淆。",
	},
	{
		ID:        "bitfs.managed.key.list_keys",
		Module:    ModuleBitFS,
		Package:   "./pkg/managedclient",
		Symbol:    "managedDaemon.listKeyPubHexes",
		Signature: "func (d *managedDaemon) listKeyPubHexes() ([]string, error)",
		Note:      "跨 key 列表业务本体：只枚举已有 key.json 的公钥目录，不修改状态。",
	},
	{
		ID:        "bitfs.managed.key.set_default",
		Module:    ModuleBitFS,
		Package:   "./pkg/managedclient",
		Symbol:    "managedDaemon.setDefaultKeyPubHex",
		Signature: "func (d *managedDaemon) setDefaultKeyPubHex(pubKeyHex string) error",
		Note:      "跨 key 切换入口：必须先校验目标 key.json 存在，再写根配置 default_key。",
	},
	{
		ID:        "bitfs.managed.key.import_encrypted",
		Module:    ModuleBitFS,
		Package:   "./pkg/managedclient",
		Symbol:    "managedDaemon.importEncryptedKeyMaterial",
		Signature: "func (d *managedDaemon) importEncryptedKeyMaterial(cipher *EncryptedKeyEnvelope) error",
		Note:      "密钥导入业务本体：校验状态并落盘密钥材料，HTTP 层只做协议编解码。",
	},
	{
		ID:        "bitfs.managed.key.export_encrypted",
		Module:    ModuleBitFS,
		Package:   "./pkg/managedclient",
		Symbol:    "managedDaemon.exportEncryptedKeyMaterial",
		Signature: "func (d *managedDaemon) exportEncryptedKeyMaterial() (*EncryptedKeyEnvelope, error)",
		Note:      "密钥导出业务本体：只负责读取密钥材料并返回，HTTP 层不参与业务判断。",
	},
	{
		ID:               "bitfs.managed.key.assert_exists",
		Module:           ModuleBitFS,
		Package:          "./pkg/managedclient",
		Symbol:           "managedDaemon.assertKeyMaterialExists",
		Signature:        "func (d *managedDaemon) assertKeyMaterialExists() error",
		ObsControlAction: "key.assert_exists",
		Note:             "只负责断言密钥文件存在；不创建、不修改。",
	},
	{
		ID:               "bitfs.managed.key.unlock_with_password",
		Module:           ModuleBitFS,
		Package:          "./pkg/managedclient",
		Symbol:           "managedDaemon.unlockWithPassword",
		Signature:        "func (d *managedDaemon) unlockWithPassword(ctx context.Context, source, password string) (unlockTicket, error)",
		ObsControlAction: "key.unlock",
		Note:             "解锁链路总入口，锁状态/运行时启动/并发竞争都围绕该函数。",
	},
	{
		ID:               "bitfs.managed.key.lock_runtime",
		Module:           ModuleBitFS,
		Package:          "./pkg/managedclient",
		Symbol:           "managedDaemon.lockRuntime",
		Signature:        "func (d *managedDaemon) lockRuntime() error",
		ObsControlAction: "key.lock",
		Note:             "运行时落锁与停机收敛入口，签名变化会破坏状态机调用面。",
	},
}
