package fnlock

// 定价业务触发入口。
var whitelistBusinessPricing = []LockedFunction{
	{
		ID:               "bitfs.clientapp.pricing.trigger_set_base",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingSetBase",
		Signature:        "func TriggerPricingSetBase(ctx context.Context, rt *Runtime, base uint64) (PricingSetBaseResult, error)",
		ObsControlAction: "pricing.set_base",
		Note:             "定价基准价触发入口，控制层和业务层通过该触发器对接。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_reset_seed",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingResetSeed",
		Signature:        "func TriggerPricingResetSeed(ctx context.Context, rt *Runtime, seedHash string) (PricingStateResult, error)",
		ObsControlAction: "pricing.reset_seed",
		Note:             "单种子定价状态重置触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_feed_seed",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingFeedSeed",
		Signature:        "func TriggerPricingFeedSeed(ctx context.Context, rt *Runtime, req PricingFeedRequest) (PricingStateResult, error)",
		ObsControlAction: "pricing.feed_seed",
		Note:             "定价样本喂入触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_set_force",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingSetForce",
		Signature:        "func TriggerPricingSetForce(ctx context.Context, rt *Runtime, req ForcePriceRequest) (PricingStateResult, error)",
		ObsControlAction: "pricing.set_force",
		Note:             "单种子强制定价触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_release_force",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingReleaseForce",
		Signature:        "func TriggerPricingReleaseForce(ctx context.Context, rt *Runtime, seedHash string) (PricingStateResult, error)",
		ObsControlAction: "pricing.release_force",
		Note:             "释放强制定价触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_run_tick",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingRunTick",
		Signature:        "func TriggerPricingRunTick(ctx context.Context, rt *Runtime, hours uint32) (PricingRunTickResult, error)",
		ObsControlAction: "pricing.run_tick",
		Note:             "定价 tick 执行触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_reconcile",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingReconcile",
		Signature:        "func TriggerPricingReconcile(ctx context.Context, rt *Runtime, seedHash string, nowUnix int64) (PricingReconcileResult, error)",
		ObsControlAction: "pricing.trigger_reconcile",
		Note:             "单种子定价对账触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_get_config",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingGetConfig",
		Signature:        "func TriggerPricingGetConfig(rt *Runtime) (PricingConfig, error)",
		ObsControlAction: "pricing.get_config",
		Note:             "读取定价全局配置触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_get_state",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingGetState",
		Signature:        "func TriggerPricingGetState(ctx context.Context, rt *Runtime, seedHash string) (PricingState, error)",
		ObsControlAction: "pricing.get_state",
		Note:             "读取单种子定价状态触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_get_audits",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingGetAudits",
		Signature:        "func TriggerPricingGetAudits(ctx context.Context, rt *Runtime, seedHash string, limit int) ([]PricingAuditItem, error)",
		ObsControlAction: "pricing.get_audits",
		Note:             "读取定价审计轨迹触发入口。",
	},
	{
		ID:               "bitfs.clientapp.pricing.trigger_list_seeds",
		Module:           ModuleBitFS,
		Package:          "./pkg/clientapp",
		Symbol:           "TriggerPricingListSeeds",
		Signature:        "func TriggerPricingListSeeds(ctx context.Context, rt *Runtime, limit int) ([]string, error)",
		ObsControlAction: "pricing.list_seeds",
		Note:             "列举定价种子触发入口。",
	},
}
